Repository DarwinPon/cs269_golf_sim, pull requests merged in 2022-01, with the labels that each got.

#24 Added md file as a wiki page template
  Game_Design_Document.md
  README.md
  assets/f422e3149a8c41130d80bec87709076.jpg
Labels: documentation, design

#30 Player balls images
  assets/player1ball.png
  assets/player2ball.png
Labels: enhancement, design

#33 Minor fix
  CODEOWNERS
Labels: bug

#73 Updating new features in to branch
  .idea/game.py
  .idea/game_objects.py
  .idea/sound.py
  .idea/start.py
  .idea/workspace.xml
  audios/ding.wav
  levels/level 1.txt
  levels/level 2.txt
  levels/level ex.txt
  pictures/acceleration_2.png
  pictures/ball.png
  pictures/ball_yellow.png
  pictures/ball_yellowbg.png
  pictures/sand.png
  rules/game_items_rule.png
  rules/game_rule.png
  rules/level_editor_rule.png
Labels: bug, enhancement

#89 All new features have passed preliminary testing
  .idea/game.py
  .idea/start.py
  .idea/workspace.xml
  levels/level 1.txt
  levels/level 2.txt
  pictures/brick_wall.png
  pictures/brick_wall_2.png
  pictures/brick_wall_3.png
  pictures/obstacle2.png
  pictures/sandpit3.png
  pictures/sandpit3_small.png
  rules/game_items.png
  rules/level_editor_rule.png
Labels: bug, enhancement
